name = "church-web-template"
type = "javascript"
account_id = ""
workers_dev = true
routes = []
zone_id = ""

[vars]
GITHUB_CLIENT_ID = "Ov23liC7BSgtlHFCzq1c"
GITHUB_CLIENT_SECRET = "e0c5af9c542e63aeb1a3fdfb97880856d574b2db"
